//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameScripts/InputSystem/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""PlayerInputMain"",
            ""id"": ""8cdfddb0-bd94-4869-830e-0f675a80a54c"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""c0e2616e-06ed-42aa-91d7-58febc7bca1d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuInput"",
                    ""type"": ""Button"",
                    ""id"": ""5ce8acb8-4c4f-424c-8aea-d65d936aa4be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackInput"",
                    ""type"": ""Button"",
                    ""id"": ""c653543d-fcdc-4335-ba48-c01eb1db058d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityInput"",
                    ""type"": ""Button"",
                    ""id"": ""8fa5709b-86c3-46c1-89c6-b5b16d9bff23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstSlot"",
                    ""type"": ""Button"",
                    ""id"": ""0c17c5c4-0280-489c-bd97-86d14ed951bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondSlot"",
                    ""type"": ""Button"",
                    ""id"": ""a1bffb6d-caf3-4e8b-9c3d-850e6a9c1b56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdSlot"",
                    ""type"": ""Button"",
                    ""id"": ""b59a5b0a-6f88-4735-b22c-a3b2f2c2a544"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourthSlot"",
                    ""type"": ""Button"",
                    ""id"": ""d5b43742-0ca3-4546-ae17-b7943d89cd7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollSlot"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8db443f1-778a-4131-90d8-320d6c0d4536"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""96445f21-1c43-4c23-9e1e-141d0761c8d7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eebf972b-77d7-4598-8c33-b60c63130daf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""742d26bc-f52e-4aec-bfa3-b917e2b02cc0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""caa71cba-eab2-4e2d-b739-451f6c4bd7e6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fc796413-047a-4407-b031-894938b3132d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a25d81e2-7aa6-4e5e-b80a-77ea8eb9e9f5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4b423ce-fd93-4700-b219-375caa744b99"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47a8990b-5c9c-49bc-aa2c-3bc294c2fc36"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""437f5c94-f4c5-4836-a24e-142ae71a1604"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32172d9b-96ec-4db0-9023-65f892051065"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ae54adc-2ca3-4306-81c6-02357609c661"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fd5e7de-c18e-47aa-acc6-137670d37e53"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourthSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d2ae781-9994-4523-b637-f2e5417e5939"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInputMain
        m_PlayerInputMain = asset.FindActionMap("PlayerInputMain", throwIfNotFound: true);
        m_PlayerInputMain_Movement = m_PlayerInputMain.FindAction("Movement", throwIfNotFound: true);
        m_PlayerInputMain_MenuInput = m_PlayerInputMain.FindAction("MenuInput", throwIfNotFound: true);
        m_PlayerInputMain_AttackInput = m_PlayerInputMain.FindAction("AttackInput", throwIfNotFound: true);
        m_PlayerInputMain_AbilityInput = m_PlayerInputMain.FindAction("AbilityInput", throwIfNotFound: true);
        m_PlayerInputMain_FirstSlot = m_PlayerInputMain.FindAction("FirstSlot", throwIfNotFound: true);
        m_PlayerInputMain_SecondSlot = m_PlayerInputMain.FindAction("SecondSlot", throwIfNotFound: true);
        m_PlayerInputMain_ThirdSlot = m_PlayerInputMain.FindAction("ThirdSlot", throwIfNotFound: true);
        m_PlayerInputMain_FourthSlot = m_PlayerInputMain.FindAction("FourthSlot", throwIfNotFound: true);
        m_PlayerInputMain_ScrollSlot = m_PlayerInputMain.FindAction("ScrollSlot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputMain
    private readonly InputActionMap m_PlayerInputMain;
    private List<IPlayerInputMainActions> m_PlayerInputMainActionsCallbackInterfaces = new List<IPlayerInputMainActions>();
    private readonly InputAction m_PlayerInputMain_Movement;
    private readonly InputAction m_PlayerInputMain_MenuInput;
    private readonly InputAction m_PlayerInputMain_AttackInput;
    private readonly InputAction m_PlayerInputMain_AbilityInput;
    private readonly InputAction m_PlayerInputMain_FirstSlot;
    private readonly InputAction m_PlayerInputMain_SecondSlot;
    private readonly InputAction m_PlayerInputMain_ThirdSlot;
    private readonly InputAction m_PlayerInputMain_FourthSlot;
    private readonly InputAction m_PlayerInputMain_ScrollSlot;
    public struct PlayerInputMainActions
    {
        private @InputMap m_Wrapper;
        public PlayerInputMainActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerInputMain_Movement;
        public InputAction @MenuInput => m_Wrapper.m_PlayerInputMain_MenuInput;
        public InputAction @AttackInput => m_Wrapper.m_PlayerInputMain_AttackInput;
        public InputAction @AbilityInput => m_Wrapper.m_PlayerInputMain_AbilityInput;
        public InputAction @FirstSlot => m_Wrapper.m_PlayerInputMain_FirstSlot;
        public InputAction @SecondSlot => m_Wrapper.m_PlayerInputMain_SecondSlot;
        public InputAction @ThirdSlot => m_Wrapper.m_PlayerInputMain_ThirdSlot;
        public InputAction @FourthSlot => m_Wrapper.m_PlayerInputMain_FourthSlot;
        public InputAction @ScrollSlot => m_Wrapper.m_PlayerInputMain_ScrollSlot;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputMain; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputMainActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputMainActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputMainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputMainActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @MenuInput.started += instance.OnMenuInput;
            @MenuInput.performed += instance.OnMenuInput;
            @MenuInput.canceled += instance.OnMenuInput;
            @AttackInput.started += instance.OnAttackInput;
            @AttackInput.performed += instance.OnAttackInput;
            @AttackInput.canceled += instance.OnAttackInput;
            @AbilityInput.started += instance.OnAbilityInput;
            @AbilityInput.performed += instance.OnAbilityInput;
            @AbilityInput.canceled += instance.OnAbilityInput;
            @FirstSlot.started += instance.OnFirstSlot;
            @FirstSlot.performed += instance.OnFirstSlot;
            @FirstSlot.canceled += instance.OnFirstSlot;
            @SecondSlot.started += instance.OnSecondSlot;
            @SecondSlot.performed += instance.OnSecondSlot;
            @SecondSlot.canceled += instance.OnSecondSlot;
            @ThirdSlot.started += instance.OnThirdSlot;
            @ThirdSlot.performed += instance.OnThirdSlot;
            @ThirdSlot.canceled += instance.OnThirdSlot;
            @FourthSlot.started += instance.OnFourthSlot;
            @FourthSlot.performed += instance.OnFourthSlot;
            @FourthSlot.canceled += instance.OnFourthSlot;
            @ScrollSlot.started += instance.OnScrollSlot;
            @ScrollSlot.performed += instance.OnScrollSlot;
            @ScrollSlot.canceled += instance.OnScrollSlot;
        }

        private void UnregisterCallbacks(IPlayerInputMainActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @MenuInput.started -= instance.OnMenuInput;
            @MenuInput.performed -= instance.OnMenuInput;
            @MenuInput.canceled -= instance.OnMenuInput;
            @AttackInput.started -= instance.OnAttackInput;
            @AttackInput.performed -= instance.OnAttackInput;
            @AttackInput.canceled -= instance.OnAttackInput;
            @AbilityInput.started -= instance.OnAbilityInput;
            @AbilityInput.performed -= instance.OnAbilityInput;
            @AbilityInput.canceled -= instance.OnAbilityInput;
            @FirstSlot.started -= instance.OnFirstSlot;
            @FirstSlot.performed -= instance.OnFirstSlot;
            @FirstSlot.canceled -= instance.OnFirstSlot;
            @SecondSlot.started -= instance.OnSecondSlot;
            @SecondSlot.performed -= instance.OnSecondSlot;
            @SecondSlot.canceled -= instance.OnSecondSlot;
            @ThirdSlot.started -= instance.OnThirdSlot;
            @ThirdSlot.performed -= instance.OnThirdSlot;
            @ThirdSlot.canceled -= instance.OnThirdSlot;
            @FourthSlot.started -= instance.OnFourthSlot;
            @FourthSlot.performed -= instance.OnFourthSlot;
            @FourthSlot.canceled -= instance.OnFourthSlot;
            @ScrollSlot.started -= instance.OnScrollSlot;
            @ScrollSlot.performed -= instance.OnScrollSlot;
            @ScrollSlot.canceled -= instance.OnScrollSlot;
        }

        public void RemoveCallbacks(IPlayerInputMainActions instance)
        {
            if (m_Wrapper.m_PlayerInputMainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputMainActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputMainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputMainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputMainActions @PlayerInputMain => new PlayerInputMainActions(this);
    public interface IPlayerInputMainActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMenuInput(InputAction.CallbackContext context);
        void OnAttackInput(InputAction.CallbackContext context);
        void OnAbilityInput(InputAction.CallbackContext context);
        void OnFirstSlot(InputAction.CallbackContext context);
        void OnSecondSlot(InputAction.CallbackContext context);
        void OnThirdSlot(InputAction.CallbackContext context);
        void OnFourthSlot(InputAction.CallbackContext context);
        void OnScrollSlot(InputAction.CallbackContext context);
    }
}
